packages:
  - packages/*
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - esbuild
  - sqlite3
  - unrs-resolver
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@naturalcycles/*'
  - vitest
  - '@vitest/*'
# trustPolicy: no-downgrade # disabled due to mitm/semver
auditConfig:
  ignoreGhsas:
    - GHSA-h755-8qp9-cq85
    - GHSA-67mh-4wv8-2f99
strictDepBuilds: true
ignoreWorkspaceCycles: true
ignorePatchFailures: false
patchedDependencies:
  semantic-release-pnpm: patches/semantic-release-pnpm.patch
