packages:
  - packages/*
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - esbuild
  - sqlite3
  - unrs-resolver
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@naturalcycles/*'
  - vitest
  - '@vitest/*'
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@5.4.21
  - semver@5.7.2
  - jose@4.15.9
  - undici@5.29.0
  - undici-types@6.21.0
auditConfig:
  ignoreGhsas:
    - GHSA-h755-8qp9-cq85
    - GHSA-67mh-4wv8-2f99
strictDepBuilds: true
ignoreWorkspaceCycles: true
ignorePatchFailures: false
patchedDependencies:
  semantic-release-pnpm: patches/semantic-release-pnpm.patch
