packages:
  - packages/*
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - esbuild
  - sqlite3
  - unrs-resolver
strictDepBuilds: true
ignoreWorkspaceCycles: true
patchedDependencies:
  semantic-release-pnpm: patches/semantic-release-pnpm.patch
  '@types/pg': patches/@types__pg.patch
