packages:
  - packages/*
catalog:
  '@typescript/native-preview': 7.0.0-dev.20260301.1
  oxlint: 1.47.0
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sqlite3
  - unrs-resolver
# minimumReleaseAge: 1440
# minimumReleaseAgeExclude:
#  - '@naturalcycles/*'
#  - vitest
#  - '@vitest/*'
#  - oxlint
#  - oxlint-tsgolint
#  - '@oxlint/*'
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@5.4.21
  - semver@5.7.2
  - jose@4.15.9
  - undici@5.29.0
blockExoticSubdeps: true
auditConfig:
  ignoreGhsas:
    - GHSA-h755-8qp9-cq85
    - GHSA-67mh-4wv8-2f99
strictDepBuilds: true
ignoreWorkspaceCycles: true
ignorePatchFailures: false
publicHoistPattern:
  - '@typescript/native-preview'
