packages:
  - packages/*
ignoredBuiltDependencies:
  - '@firebase/util'
  - protobufjs
onlyBuiltDependencies:
  - '@biomejs/biome'
  - better-sqlite3
  - esbuild
  - sqlite3
  - unrs-resolver
patchedDependencies:
  semantic-release-pnpm: patches/semantic-release-pnpm.patch
  '@vitest/expect': patches/@vitest__expect.patch
